"""cv import: import_sessions table, generation_history import_session_id

Revision ID: 078efa20debf
Revises: 9f20624ebdfd
Create Date: 2026-08-08 22:17:52.200247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '078efa20debf'
down_revision: Union[str, Sequence[str], None] = '9f20624ebdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', 'failed', name='import_session_status'), nullable=False),
    sa.Column('proposed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_sessions_profile_id'), 'import_sessions', ['profile_id'], unique=False)
    op.add_column('generation_history', sa.Column('import_session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_generation_history_import_session_id',
        'generation_history', 'import_sessions', ['import_session_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_generation_history_import_session_id', 'generation_history', type_='foreignkey'
    )
    op.drop_column('generation_history', 'import_session_id')
    op.drop_index(op.f('ix_import_sessions_profile_id'), table_name='import_sessions')
    op.drop_table('import_sessions')
    # ### end Alembic commands ###
    # Postgres does not drop named ENUM types when the last column using them
    # is dropped -- without this, re-running upgrade() after this downgrade
    # fails with "type already exists".
    sa.Enum(name='import_session_status').drop(op.get_bind(), checkfirst=True)
