"""file storage: files table, certification/achievement attachments

Revision ID: 1b7891c224a8
Revises: 287d7080ec63
Create Date: 2026-08-05 16:02:26.256274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7891c224a8'
down_revision: Union[str, Sequence[str], None] = '287d7080ec63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('avatar', 'certificate', 'achievement', name='file_purpose'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_profile_id'), 'files', ['profile_id'], unique=False)
    op.add_column('achievements', sa.Column('file_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_achievements_file_id_files', 'achievements', 'files', ['file_id'], ['id'])
    op.add_column('certifications', sa.Column('file_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_certifications_file_id_files', 'certifications', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_certifications_file_id_files', 'certifications', type_='foreignkey')
    op.drop_column('certifications', 'file_id')
    op.drop_constraint('fk_achievements_file_id_files', 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'file_id')
    op.drop_index(op.f('ix_files_profile_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
    # Postgres does not drop named ENUM types when the last column using them
    # is dropped -- without this, re-running upgrade() after this downgrade
    # fails with "type already exists".
    sa.Enum(name='file_purpose').drop(op.get_bind(), checkfirst=True)
