"""ai engine: prompt_history, generation_history, ai_provider_logs

Revision ID: 21aeaaceda48
Revises: c83d32f933ed
Create Date: 2026-08-05 22:44:13.308589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aeaaceda48'
down_revision: Union[str, Sequence[str], None] = 'c83d32f933ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_history',
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose', 'version')
    )
    op.create_index(op.f('ix_prompt_history_prompt_hash'), 'prompt_history', ['prompt_hash'], unique=False)
    op.create_table('generation_history',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('prompt_history_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='generation_status'), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['prompt_history_id'], ['prompt_history.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_history_profile_id'), 'generation_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_generation_history_resume_id'), 'generation_history', ['resume_id'], unique=False)
    op.create_table('ai_provider_logs',
    sa.Column('generation_history_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_history_id'], ['generation_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_provider_logs_generation_history_id'), 'ai_provider_logs', ['generation_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_provider_logs_generation_history_id'), table_name='ai_provider_logs')
    op.drop_table('ai_provider_logs')
    op.drop_index(op.f('ix_generation_history_resume_id'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_profile_id'), table_name='generation_history')
    op.drop_table('generation_history')
    op.drop_index(op.f('ix_prompt_history_prompt_hash'), table_name='prompt_history')
    op.drop_table('prompt_history')
    # ### end Alembic commands ###
    # Postgres does not drop named ENUM types when the last column using them
    # is dropped -- without this, re-running upgrade() after this downgrade
    # fails with "type already exists".
    sa.Enum(name='generation_status').drop(op.get_bind(), checkfirst=True)
