"""extended career data: achievements, certifications, awards, research, volunteer, leadership, orgs, languages, references, hackathons, competitions, patents

Revision ID: 287d7080ec63
Revises: 84d977e722a6
Create Date: 2026-08-05 11:26:51.695743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287d7080ec63'
down_revision: Union[str, Sequence[str], None] = '84d977e722a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('date_achieved', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_profile_id'), 'achievements', ['profile_id'], unique=False)
    op.create_table('awards',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_profile_id'), 'awards', ['profile_id'], unique=False)
    op.create_table('certifications',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuing_organization', sa.String(length=200), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=150), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_profile_id'), 'certifications', ['profile_id'], unique=False)
    op.create_table('competitions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_profile_id'), 'competitions', ['profile_id'], unique=False)
    op.create_table('hackathons',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathons_profile_id'), 'hackathons', ['profile_id'], unique=False)
    op.create_table('languages',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.Enum('basic', 'conversational', 'professional', 'fluent', 'native', name='language_proficiency'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_profile_id'), 'languages', ['profile_id'], unique=False)
    op.create_table('leadership_roles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leadership_roles_profile_id'), 'leadership_roles', ['profile_id'], unique=False)
    op.create_table('organizations',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_profile_id'), 'organizations', ['profile_id'], unique=False)
    op.create_table('patents',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('filed', 'pending', 'granted', 'rejected', name='patent_status'), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_profile_id'), 'patents', ['profile_id'], unique=False)
    op.create_table('references',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_profile_id'), 'references', ['profile_id'], unique=False)
    op.create_table('research',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('publication_venue', sa.String(length=200), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_profile_id'), 'research', ['profile_id'], unique=False)
    op.create_table('volunteer_experiences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_experiences_profile_id'), 'volunteer_experiences', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_experiences_profile_id'), table_name='volunteer_experiences')
    op.drop_table('volunteer_experiences')
    op.drop_index(op.f('ix_research_profile_id'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_references_profile_id'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_patents_profile_id'), table_name='patents')
    op.drop_table('patents')
    op.drop_index(op.f('ix_organizations_profile_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_leadership_roles_profile_id'), table_name='leadership_roles')
    op.drop_table('leadership_roles')
    op.drop_index(op.f('ix_languages_profile_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_hackathons_profile_id'), table_name='hackathons')
    op.drop_table('hackathons')
    op.drop_index(op.f('ix_competitions_profile_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_certifications_profile_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_awards_profile_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_achievements_profile_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
    # Postgres does not drop named ENUM types when the last column using them
    # is dropped -- without this, re-running upgrade() after this downgrade
    # fails with "type already exists".
    sa.Enum(name='language_proficiency').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='patent_status').drop(op.get_bind(), checkfirst=True)
