"""companion generators: cover_letters, linkedin_generations

Revision ID: 9f20624ebdfd
Revises: 2563f4676b9f
Create Date: 2026-08-06 23:59:12.694482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f20624ebdfd'
down_revision: Union[str, Sequence[str], None] = '2563f4676b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_generations',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=150), nullable=True),
    sa.Column('headline', sa.String(length=250), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_generations_profile_id'), 'linkedin_generations', ['profile_id'], unique=False)
    op.create_table('cover_letters',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('hiring_manager', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_profile_id'), 'cover_letters', ['profile_id'], unique=False)
    op.add_column('generation_history', sa.Column('cover_letter_id', sa.UUID(), nullable=True))
    op.add_column('generation_history', sa.Column('linkedin_generation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_generation_history_cover_letter_id_cover_letters',
        'generation_history', 'cover_letters', ['cover_letter_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_generation_history_linkedin_generation_id',
        'generation_history', 'linkedin_generations', ['linkedin_generation_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_generation_history_linkedin_generation_id',
        'generation_history', type_='foreignkey',
    )
    op.drop_constraint(
        'fk_generation_history_cover_letter_id_cover_letters',
        'generation_history', type_='foreignkey',
    )
    op.drop_column('generation_history', 'linkedin_generation_id')
    op.drop_column('generation_history', 'cover_letter_id')
    op.drop_index(op.f('ix_cover_letters_profile_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index(op.f('ix_linkedin_generations_profile_id'), table_name='linkedin_generations')
    op.drop_table('linkedin_generations')
    # ### end Alembic commands ###
